document.write("<div class='footer-in'>");
document.write("	<ul class='terms'>");
document.write("		<li><a href='/html/member/personalInfo.html'>개인정보처리방침</a></li>");
document.write("		<li><a href='/html/member/emailInfo.html'>이메일무단수집거부</a></li>");
document.write("	</ul>");
document.write("	<ul class='relation'>");
//document.write("		<li style='margin-right:7px;'><a href='http://kostat.go.kr' target='_blank'><img src='/img/common/f_link2.png' alt='통계청' title='통계청' /></a></li>");
//document.write("		<li style='margin-right:7px;'><a href='http://kosis.kr' target='_blank'><img src='/img/common/f_link5.png' alt='KOSIS' title='KOSIS' /></a></li>");
//document.write("		<li style='margin-right:7px;'><a href='http://mdss.kostat.go.kr' target='_blank'><img src='/img/common/f_link1.png' alt='MDSS' title='MDSS' /></a></li>");
//document.write("		<li style='margin-right:7px;'><a href='http://index.go.kr' target='_blank'><img src='/img/common/f_link4.png' alt='e-나라지표' title='e-나라지표' /></a></li>");
//document.write("		<li style='margin-right:7px;'><a href='http://kssc.kostat.go.kr/ksscNew_web/index.jsp' target='_blank'><img src='/img/common/f_link6.png' alt='통계분류' title='통계분류' /></a></li>");
//document.write("		<li><a href='http://sgis1.kostat.go.kr/OpenAPI2/contents/sub03.vw' target='_blank'><img src='/img/common/f_link3.png' alt='s-OpneAPI' title='s-OpneAPI' /></a></li>");
document.write("		<li style='margin-right:7px;'><a href='http://kostat.go.kr' target='_blank'>통계청 |</a></li>");
document.write("		<li style='margin-right:7px;'><a href='http://kosis.kr' target='_blank'>KOSIS |</a></li>");
document.write("		<li style='margin-right:7px;'><a href='http://mdss.kostat.go.kr' target='_blank'>MDSS |</a></li>");
document.write("		<li style='margin-right:7px;'><a href='https://kssc.kostat.go.kr:8443/ksscNew_web/index.jsp' target='_blank'>통계분류</a></li>");
document.write("	</ul>");
document.write("	<div class='info'>");
document.write("		<p class='address'>(302-702)대전광역시 서구 청사로 189</p>");
document.write("		<dl class='tel'>");
document.write("			<dt>통계청콜센터 :</dt>");
document.write("			<dd>02)2012-9114</dd>");
document.write("			<dt>관리자 :</dt>");
document.write("			<dd>042)481-2248</dd>");
document.write("			<dt>자료제공담당자 :</dt>");
document.write("			<dd>(042)481-2438</dd>");
document.write("		</dl>");
document.write("	</div>");
document.write("	<div class='mobile_footer'>");
document.write("		<div class='info'>");
document.write("			<p class='address'>(302-702)대전광역시 서구 청사로 189</p>");
document.write("			<p class='address'>통계청콜센터 : 02)2012-9114</p>");
document.write("			<p class='address'관리자 : 042)481-2248</p>");
document.write("			<p class='address'>자료제공담당자 : (042)481-2438</p>");
document.write("		</div>");
document.write("		<p class='copyright'>COPYRIGHT STATISTICS KOREA. ALL RIGHTS RESERVED SINCE 2014</p>");
document.write("		<ul class='relation'>");
//document.write("		<li style='margin-right:7px;'><a href='http://kostat.go.kr' target='_blank'><img src='/img/common/f_link2.png' alt='통계청' title='통계청' /></a></li>");
//document.write("		<li style='margin-right:7px;'><a href='http://kosis.kr' target='_blank'><img src='/img/common/f_link5.png' alt='KOSIS' title='KOSIS' /></a></li>");
//document.write("		<li style='margin-right:7px;'><a href='http://mdss.kostat.go.kr' target='_blank'><img src='/img/common/f_link1.png' alt='MDSS' title='MDSS' /></a></li>");
//document.write("		<li style='margin-right:7px;'><a href='https://kssc.kostat.go.kr:8443/ksscNew_web/index.jsp' target='_blank'><img src='/img/common/f_link6.png' alt='통계분류' title='통계분류' /></a></li>");
document.write("			<li style='margin-right:7px;'><a href='http://kostat.go.kr' target='_blank'>통계청 |</a></li>");
document.write("			<li style='margin-right:7px;'><a href='http://kosis.kr' target='_blank'>KOSIS |</a></li>");
document.write("			<li style='margin-right:7px;'><a href='http://mdss.kostat.go.kr' target='_blank'>MDSS |</a></li>");
document.write("			<li style='margin-right:7px;'><a href='https://kssc.kostat.go.kr:8443/ksscNew_web/index.jsp' target='_blank'>통계분류</a></li>");
document.write("		</ul>");
document.write("	</div>");
document.write("</div>"); 